#!/bin/bash
# Deploy the pgtgpigpio Debian package to the Raspberry Pi.
# Run ./build then ./package first to produce the .deb file.

PKGNAME=pgtgpigpio
VERSION=1.0.0
ARCH=arm64
DEB="${PKGNAME}_${VERSION}_${ARCH}.deb"

scp "./${DEB}" pi@192.168.111.241:/home/pi/${DEB}
echo "On Pi run: sudo apt install /home/pi/${DEB}"
